name: vizbert
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cudatoolkit=10.1.243
  - freetype=2.9.1
  - intel-openmp=2020.0
  - jpeg=9b
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.2
  - ninja=1.9.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1d
  - pillow=7.0.0
  - pip=20.0.2
  - python=3.7.6
  - pytorch=1.4.0
  - readline=7.0
  - setuptools=46.0.0
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - torchvision=0.5.0
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - boto3==1.12.19
    - botocore==1.15.19
    - chardet==3.0.4
    - click==7.1.1
    - conllu==2.3
    - docutils==0.15.2
    - filelock==3.0.12
    - idna==2.9
    - jmespath==0.9.5
    - joblib==0.14.1
    - python-dateutil==2.8.1
    - regex==2020.2.20
    - requests==2.23.0
    - s3transfer==0.3.3
    - sacremoses==0.0.38
    - sentencepiece==0.1.85
    - tokenizers==0.5.2
    - tqdm==4.43.0
    - transformers==2.5.1
    - urllib3==1.25.8
